# **Store Information**
- Store DataTable 에 추가될 **Text 내용** 확인하기
- Store DataTable 에 추가될 **Image 내용** 확인하기

## **1 Editing the Store Code**
Store Code 정보 추가하기

In [1]:
import pandas as pd
file_name = '../media/csv/backup/store_org.csv'
table_source = pd.read_csv(file_name, header=None)
table_source.tail(3)

,0,1,2,3,4,5,6,7,8,9,10
141,감성예술교육센터,주정민,학원,서비스,김미숙,010-4736-3937,낙성대역16길 13,서울특별시 관악구 낙성대역16길 13,서울특별시 관악구 봉천동 196-58,126.964815,37.473449
142,신현선무관,임우현,학원,서비스,안현석,010-2275-5616,"장군봉1길 45, 2층",서울특별시 관악구 장군봉1길 45,서울특별시 관악구 봉천동 927-18,126.942606,37.481743
143,위더스,안다혜,핸드폰매장,서비스,손지정,010-9248-8176,"양녕로 39, 1층",서울특별시 관악구 양녕로 39,서울특별시 관악구 봉천동 899-17,126.946719,37.485528

In [2]:
import re
file_name = '../media/csv/backup/store_code.csv'
token_group, token_mid = re.compile(r"[A-C]{1}"), re.compile(r"-[\d]{1,2}-")
result_code, result_artist = [], []
table_code = pd.read_csv(file_name, header=None)
for _ in table_code[0]:
    group, number_store = "".join(token_group.findall(_)), int(_[-1:])
    number_middle = int("".join(token_mid.findall(_)).replace('-',''))
    code_artist = f"{group}{number_middle:02d}"
    code = f"{code_artist}{number_store}"
    result_artist.append(code_artist); result_code.append(code)
table_code[0] = result_code
# table_code.insert(0,'artist',result_artist)
table_code.head(3)

      0       1
0  A011  영진떡방앗간
1  A012    카페네온
2  A013   영진부동산

In [3]:
# table_source 에 코드 추가하기
result_artist = []
result_store = []
for _ in table_source[0]:
    instance = table_code[table_code[1] == _]
    index_integer = instance.index.astype(int).values[0]
    # result_artist.append(table_code.loc[index_integer,'artist'])
    result_store.append(table_code.loc[index_integer,0])
table_source.insert(0,'index', result_store)
# table_source.insert(0,'artist', result_artist)
# table_source = table_source.sort_values(['artist','store']).reset_index(drop=True)
table_source = table_source.sort_values('index').reset_index(drop=True)
table_source.head()

,index,0,1,2,3,4,5,6,7,8,9,10
0,A011,영진떡방앗간,박현철,떡집,휴게음식,박명일,010-8507-6657,난향길 14,서울특별시 관악구 난향길 14,서울특별시 관악구 신림동 676-36,126.918079,37.462919
1,A012,카페네온,박현철,카페,휴게음식,유민영,010-9688-7097,난향길 24,서울특별시 관악구 난향길 24 현경빌딩,서울특별시 관악구 신림동 676-42 현경빌딩,126.917727,37.462847
2,A013,영진부동산,박현철,부동산,생활잡화,서청,010-3244-6816,난향길 14,서울특별시 관악구 난향길 14,서울특별시 관악구 신림동 676-36,126.918001,37.462786
3,A014,김현애보습학원,박현철,학원,서비스,김현애,010-4192-2239,"난향길 14, 2층",서울특별시 관악구 난향길 14,서울특별시 관악구 신림동 676-36,126.917923,37.462653
4,A021,마음이 움직이는 토탈공예,나서윤,기타판매,서비스,장경애,010-6753-2523,"난향길 14, 1층",서울특별시 관악구 난향길 14,서울특별시 관악구 신림동 676-36,126.917845,37.462521

In [4]:
table_source[table_source[0]=='진아네닭갈비'] # A113

,index,0,1,2,3,4,5,6,7,8,9,10
42,A113,진아네닭갈비,전은주,음식점,음식점,김종숙,010-4333-3297,"신림로7나길 42, 1층",서울특별시 관악구 신림로7나길 42,서울특별시 관악구 신림동 241-77,126.939191,37.469435

## **2 Raw Store Code**
Store Code 세부정보 가공하기

In [5]:
import re
import pandas as pd
file_name = '../media/csv/backup/store_text.csv'
tokenizer1 = re.compile(r'[A-C]_[\d]{2}_[\d]{1}')
tokenizer2 = re.compile(r'[A-C]_[\d]{2}')
table_data = pd.read_csv(file_name, header=None)
# Index Name Field 추가하기
table_data.insert(0, 'index', ["".join(tokenizer1.findall(_)).replace('_', '')  for _ in table_data[0]])
# table_data.insert(0, 'artist', ["".join(tokenizer2.findall(_)).replace('_', '')  for _ in table_data[0]])
# 분류 Field 이름으로 변경하기
table_data[0] = [_.replace("".join(tokenizer1.findall(_))+"_", "")  for _ in table_data[0]]
table_data_temp = table_data[table_data['index']=='A113']
table_data_temp

    index               0                                                  1
462  A113   banner_txt_01                                   너는 오늘 닭갈비가 먹고싶다!
463  A113   banner_txt_02                                             진아네닭갈비
464  A113   banner_txt_03                                           X 전은주 작가
465  A113        title_01                                  오늘도 먹고 싶은 진아네 닭갈비
466  A113        title_02  진아네닭갈비 사장님도 처음엔 의욕도 없으셨고 사업 자체에 어떤 희망과 기대도 없으신...
467  A113     image01_txt  가게의 첫 인상은 오래된 간판과 외벽 그리고 쓰레기들로 인해 손님들이 접근하기 쉽지...
468  A113     image02_txt  하나의 목표! 나는 오늘 닭갈비를 먹어야겠다! 일단 외부가 깔끔하고 눈에 띄며 밝은...
469  A113     image03_txt  사장님이 나이가 있으셨지만 트랜디한 시안을 보여 드렸을 때도 흔쾌히 컨펌을 해주셨고...
470  A113  profile_txt_01                                                전은주
471  A113  profile_txt_02                                      광고디자인, 그래픽디자인
472  A113  profile_txt_03  시각디자인을 전공했고 실무에선 온라인광고대행사를 다니며 실무를 경험했습니다. 현재는...

## **3 Merging the Store Code**
Store Table 조합하여 만들기
```
데이터 일치하는지 여부 확인하기
```

In [6]:
# Code 와 Text Table 값의 일치여부 확인하기
# 21.01.31 확인 완료

# _ = {table_source[table_source['index'] == _][0].values[0].strip() : 
#  table_data[(table_data['index']==_) & ((table_data[0]=='banner_txt_02'))][1].values[0].strip()
#  for _ in table_data['index']}

In [7]:
resultTable = []
for _ in table_source['index']:
    instance = table_data[table_data['index']== _]
    banner = instance[instance[0] == 'banner_txt_01'][1].values[0].strip()
    title = instance[instance[0] == 'title_01'][1].values[0].strip()
    title_script = instance[instance[0] == 'title_02'][1].values[0].strip()
    image1 = instance[instance[0] == 'image01_txt'][1].values[0].strip()
    image2 = instance[instance[0] == 'image02_txt'][1].values[0].strip()
    image3 = instance[instance[0] == 'image03_txt'][1].values[0].strip()
    resultTable.append([banner, title, title_script, image1, image2, image3])
tableTemp = pd.DataFrame(resultTable)
tableTemp.columns = ["banner", "title", "script", "text1", "text2", "text3"]
table_store = pd.merge(table_source, tableTemp, left_index=True, right_index=True,how='right').iloc[:,1:]
# table_store.to_csv("../media/csv/store.csv", header=None, index=None)
table_store.tail()

,0,1,2,3,4,5,6,7,8,9,10,banner,title,script,text1,text2,text3
139,행운부동산,심효선,부동산,생활잡화,권혁숙,010-8000-7254,남부순환로208길 17-4,서울특별시 관악구 남부순환로208길 17-4,서울특별시 관악구 봉천동 921-32,126.943539,37.481258,"4개의 하트, 행운부동산","4개의 하트, 행운부동산",첫 만남부터 사장님께서 전적으로 믿고 받아들여주셔서 큰 이슈 없이 진행할 수 있었다...,"샷시가 엄청 오래됨, 사장님께서 직접 설치와 보수를 하여 마감이 깔끔하지 않음",행운이라는 상호명에서 착안한 네잎클로버와 그린 색상을 주색으로 사용하여 깨끗하고 밝...,"간판 교체, 윈도우 시트 교체, 샷시 실리콘 교체 및 단열보강"
140,SJ베이커리,임우현,제과점,휴게음식,안상재,010-4415-3243,장군봉1길 46,서울특별시 관악구 장군봉1길 46,서울특별시 관악구 봉천동 928-5,126.942533,37.481557,친근한 동네빵집,친근한 동네빵집 에스제이 베이커리,처음엔 점포주가 사업진행을 포기하려 했으나 사업의 긍정적인 측면으로 설득하여 진행하...,"가게의 규모에 비해 많은 세 개의 간판(전면1, 돌출2)이 오랜시간 동안 전구 없이...","점포주의 의견대로 무난한 디자인으로 방향을 잡았다. 기본적으로 갈색계열과 주황색, ...",기존의 흰 바탕에 작은 글자들이 있던 간판보단 더 가독성이 좋아졌고 간판 세 개 모...
141,신현선무관,임우현,학원,서비스,안현석,010-2275-5616,"장군봉1길 45, 2층",서울특별시 관악구 장군봉1길 45,서울특별시 관악구 봉천동 927-18,126.942606,37.481743,마리텔 출연 사범님이 가르치는 합기도,마리텔 출연 사범님이 가르치는 합기도,"간판 등 큰 항목 외에 세부적으로 실측, 제작해야 할 시트지 등이 많았고 수작업이 ...","로고(파일)의 부재, 두 간판의 전구교체 및 천갈이 필요, 계단 내 대형 게시판 방...",점포주 요청대로 기본적으로 귀엽거나 가볍지 않은 분위기로 글자의 경우 필기체(붓글씨...,"일단 천갈이 후 전면, 돌출간판에 LED전구를 새로 부착하여 시인성이 매우 높아졌으..."
142,임서하헤어마벨,임우현,미용업,생활잡화,임서하,010-8689-8650,장군봉1길 29,서울특별시 관악구 장군봉1길 29,서울특별시 관악구 봉천동 930-3,126.941729,37.481842,친절한 사장님이 해주시는 머리,친절한 사장님이 해주시는 머리 임서하 헤어마벨,개인적으로 기존과 다른 새로운 디자인으로 변화시키고 싶었으나 점포주가 큰 변화를 원...,타 업체에서 시공한 지 얼마 되지 않았지만 마감문제로 간판의 오염이 기간에 비해 심...,점포주는 큰 변화보다 기존의 이미지를 유지하며 깔끔하게 작업이 되길 희망하였다. 그...,타점포와는 달리 간판 자체를 교체함으로써 단순 천갈이에 비해 훨씬 효과적인 결과를 ...
143,정가한정식,임우현,음식점,음식점,유영옥,010-5331-7715,남부순환로 1710,서울특별시 관악구 남부순환로 1710 이너스빌딩,서울특별시 관악구 봉천동 945-10 이너스빌딩,126.939874,37.482753,넓고 쾌적한 점포를 더욱 인상깊게,넓고 쾌적한 점포를 더욱 인상깊게 정가 한정식,첫 미팅 후 상담했던 점포주 내외의 의견이 달라 두 번쨰 미팅부터 방향을 바꾸었다....,가게의 규모는 상당히 크고 까끔했지만 기존간판의 야간 시 시인성이 떨어지고 타점포에...,점포주의 요청으로 크지 않아도 시인성이 좋은 붉은색 간판으로 작업하였고 당시 현수막...,"붉은색의 코너간판은 주간에나 야간, 특히 야간엔 시인성이 좋아졌고 큰 벽화는 시각적..."

## **4 Checking the DataSet**
원본 Table 에서 내용 확인해서 색인 만들기

In [8]:
name_table_dict = {}
check = 0
for _ in sorted(set(table_data['index'])):
    instance = table_data[table_data['index']==_]
    name_store = instance[instance[0]=='banner_txt_02'][1].values[0]
    # name_store = instance.iloc[1,2]# .values[0]
    name_artist = instance[instance[0]=='profile_txt_01'][1].values[0]
    # name_artist = instance.iloc[-3, 2]#.values[0]
    if name_artist not in name_table_dict.keys():
        name_table_dict[name_artist] = []
        name_table_dict[name_artist].append(name_store.strip())
    else:
        name_table_dict[name_artist].append(name_store.strip())
len(name_table_dict)

37

In [9]:
name_table_dict

{'박현철': ['영진떡집', '카페네온', '영진부동산', '김현애보습학원'],
 '나서윤': ['꿈꾸는 세상', '난향면옥', '기똥찬 수제햄버거&컵밥', '모꼬지'],
 '조유진': ['옥이네', '같이한끼', '행복한 식당', '신선포차'],
 '박은미': ['공주식당', '예지사', '시골막걸리', '파스텔'],
 '정수정': ['보석당', '21세기 축산물 백화점', '명태어장', '명성부동산'],
 '이경민': ['컴플러스', '싸군마켓', '건영하이퍼마켓', '윤아미용실'],
 '김송리': ['옆집', '알라딘', '한울타리 365DC몰', '메탈브론즈'],
 '이승희': ['오투헤어', '윤선 음악교습소', '싱싱생선', '빵하우스'],
 '김예은': ['신대성각', 'KNC숯불바베큐', '대가왕돈카츠', '녹두부동산'],
 '김수민': ['에이큐미용타운', '아이비스터디카페', '커피더알', '김치다움'],
 '전은주': ['광태소극장', '돌초밥', '진아네닭갈비'],
 '허지예': ['으뜸 24시 마트', '최상위에듀 수학교습소', '탕가네', '포도나무 김밥'],
 '조연화': ['정육의 달인', '자연색', '아림약국', '롤앤밥스'],
 '조영경': ['떡본김에 분식', '이원주 갈비찜', '전설의 떡볶이'],
 '강주희': ['셀프 24시 빨래방', '스태미나 식당', '한양왕족발', '카페로프트'],
 '함연주': ['니와', '카페딜', '휘가로', '아이편한안경콘택트'],
 '최유나A': ['성도 문구', '까까머리방', '샴푸보이', '카페 나날의 행복'],
 '이은비': ['완산포차', '큐슈라멘', '코코멍냥'],
 '최유나B': ['오렌지 헤어', '미나리 생삼겹', '루나 뮤직', '수라간 반찬'],
 '최혜지': ['신림탑텐실내양궁장', '막불감동', '복돈이부추삼겹살', '볼앤볼드 스튜디오'],
 '이성현': ['중앙부동산', '엠알기획', '코끼리 마트'],
 '오진현': ['모든홍삼', '종로떡집', '이화아뜰리에', '김원화 미용실'],
 '정다은': ['요고조고', '목포산낙지 해물철판', '삼보샷시기업', '라라헤어'],
 '김희수': ['에스네일', '새한사', '도우다 베이커리', '생황과 사람들'],
 '강인태': ['달콤상자', '아지트', '신림가일', '왕성베이커리'],
 '최윤혜': ['선녀와 나무꾼', '장수우렁불백', '뚱띵이왕갈비', '육교식당'],
 '한지연': ['스마일 부동산', '블랑도우', '다경 꽃차 교육원', 'JD las 실버 주얼리 공방'],
 '주정민': ['아다지오 et 음악학원', '감성예술교육센터', '웰빙하우스', '명문삼겹살'],
 '노준태': ['수제비손칼국수', '카페 청춘랜드', '마노아김밥', '솔이네커피볶는집'],
 '소혜정': ['통큰 바다장어', '롤링락', '카페 청신호', '총각네 정육점'],
 '박진호': ['명가떡방', '한상궁순대국', '시온테크(이안컴퓨터)', '머리하는날'],
 '안소율': ['멕스칸떡볶이', '행운동떡집', '홍두깨손칼국수', '이팔길칠공'],
 '김도영': ['서프파이어', 'ROOM601', '5월 그리고 11월', '마포식당'],
 '권혁준': ['달빛', '한마음 문구점', '커피 블루', '자상한 시간'],
 '안다혜': ['위더스', '퀸즈에스테틱', '드림서점', '먹고가세'],
 '심효선': ['머리깍자', '불타는 왕십리 곱창', '콩쥐팥쥐 떡집', '행운부동산'],
 '임우현': ['에스제이 베이커리', '신현선무관', '임서하 헤어마벨', '정가 한정식']}

In [10]:
result = []
for k,v in name_table_dict.items():
    result += v
len(result)

144